Update the jattach version to 2.1
apache/solr-docker pull request #14
Opened 2022-12-01 16:26 UTC by ritchieaxon

jattach version 1.5 is out of date, currently the latest one is 2.1, creating this PR for solr team to consider to upgrade it due to security concern

2022-12-01 16:57 UTC, HoustonPutman commented
Are there compatibility concerns between jattach v1 and v2?

2022-12-01 17:06 UTC, ritchieaxon commented
> Are there compatibility concerns between jattach v1 and v2?

https://github.com/apangin/jattach/releases
here is their release note, looks like they added support for OpenJ9 support

2022-12-01 18:47 UTC, HoustonPutman commented
Ok, so our 9.x images so far are running Ubuntu 20.20 (focal fossa). The jattach version for this ubuntu release is `1.5`, so if users were upgrading from the 8.11 image to 9.1, they would be downgrading jattach. I think that what we should do is upgrade the ubuntu version for the next Solr release (9.2), then when that is done we can upgrade jattach. Thoughts?

2022-12-01 18:58 UTC, ritchieaxon commented
> Ok, so our 9.x images so far are running Ubuntu 20.04 (focal fossa). The jattach version for this ubuntu release is `1.5`, so if users were upgrading from the 8.11 image to 9.1, they would be downgrading jattach. I think that what we should do is upgrade the ubuntu version for the next Solr release (9.2), then when that is done we can upgrade jattach. Thoughts?
> 
> https://launchpad.net/ubuntu/+source/jattach

What if there are users cannot really upgrade to 9.2? is it possible you guys can do it for 8.11 as well?

2022-12-01 19:03 UTC, HoustonPutman commented
Oh what I meant is that when 9.2 has an upgraded jattach, we can upgrade the 8.11 jattach. so that when users go from 8->9 , they don't have to downgrade.

2022-12-01 19:04 UTC, ritchieaxon commented
> Oh what I meant is that when 9.2 has an upgraded jattach, we can upgrade the 8.11 jattach. so that when users go from 8->9 , they don't have to downgrade.

Oh yeah that will do, any timeline when that will happen? :)

2022-12-02 01:18 UTC, janhoy commented on 8.11-slim/Dockerfile
>    echo >jattach.sha512 "d8eedbb3e192a8596c08efedff99b9acf1075331e1747107c07cdb1718db2abe259ef168109e46bd4cf80d47d43028ff469f95e6ddcbdda4d7ffa73a20e852f9  jattach"; \
I suppose you need to update line 23 as well with the sha of the new binary?

2022-12-07 20:34 UTC, ritchieaxon commented
Hi @HoustonPutman, wondering if you have a timeline to update the jattach?

2022-12-07 21:28 UTC, janhoy requested changes
Please address my review comment - and update the checksum too

2022-12-07 21:46 UTC, HoustonPutman commented
@janhoy did you see my earlier comment. I don't think its a good idea to update the jattach for 8.11 while we cannot update it for 9.1.

We can upgrade it in Solr for a 9.2 release, and once that is available we can upgrade the version in the 8.11 image.

> Hi @HoustonPutman, wondering if you have a timeline to update the jattach?

I do not, but we will not have a 9.2 release available until at least February, so thats the earliest we will likely see this updated.

2022-12-07 22:18 UTC, janhoy commented
I agree with the proposed timeline. First 9.2, then this can go in.

2023-01-06 19:34 UTC, janhoy commented
@ritchieaxon Do you want to update the checksum to match the new version. Then, once Solr 9.2 ships, probably in February-ish, we can merge this. I'll convert it to a draft for now, to remind us that it should not be merged.

2023-01-11 09:21 UTC, janhoy commented
Tracked in https://issues.apache.org/jira/browse/SOLR-16523

2023-03-28 19:19 UTC, HoustonPutman commented
Ok so Solr 9.2 officially has jattach 2.0 built in:

```
❯ docker run -it --rm solr:9.2 jattach --version
jattach 2.0 built on Aug 16 2021
```

So we can put jattach 2.0 in 8.11 now, but not jattach 2.1

2023-03-31 22:56 UTC, janhoy approved these changes

2023-03-31 23:20 UTC, janhoy commented
Think this is good now.

2023-03-31 23:25 UTC, merged